### ISSUE TITLE
Address shared snippets/code in pathogen builds

### ISSUE THREAD

**Issue by tsibley** [nextstrain/zika#2]
Not sure what the best approach is here, there are several, but we should eventually address things like: https://github.com/nextstrain/zika/blob/master/Snakefile#L4-L23

**Comment by tsibley** [comment]
After consideration, my current thought is to create a `nextstrain-build` Python package which provides a module structure like:

```
nextstrain/
  build/
    __init__.py
    config.py
    ...
```

which is expected to be installed. This would let Snakefiles import useful functions like:

```python
from nextstrain.build.config import field_map
```

Thoughts?

**Comment by tsibley** [comment]
augur version checking could be wrapped up into a routine in this `nextstrain-build` package, for example:

```python
from nextstrain.build.util import assert_augur_version

assert_augur_version("3.0.0")
```

**Comment by genehack** [comment]
I'm going to go ahead and close this issue:

* it is 5+ years old
* it isn't assigned to anybody
* it feels like recent "workflows-as-programs" discourse addresses (and somewhat supplants) this issue

If anybody dis-agrees, please reopen the issue.
