### ISSUE TITLE
Investigate methods to declare expected augur/fauna/… versions

### ISSUE THREAD

**Issue by tsibley** [nextstrain/zika#3]
Not sure what this should look like, but it might be a very useful thing to have.  On the other hand, if we're good at preserving backwards compat once augur stabilizes a bit, this may be mostly a non-issue.  A topic to think about and discuss.

**Comment by genehack** [comment]
Closing this out for reasons similar to #2 

As with that issue, please re-open if there's disagreement about closing.

**Comment by victorlin** [comment]
> A topic to think about and discuss.

+1! https://github.com/nextstrain/public/issues/7 has some related discussion (6 years later).

**Comment by j23414** [comment]
Just going to mention that zika pipeline no longer uses "fauna" since [January 2024]( https://github.com/nextstrain/zika/blob/649e495a6b181c004bacae26ea4507fc6989abc5/CHANGELOG.md?plain=1#L13)
