### ISSUE TITLE
Drop accession workaround when nextstrain/augur 1384 is solved

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/zika#32]
Originally from https://github.com/nextstrain/zika/pull/28#discussion_r1457994982

**Comment by j23414** [comment]
A related https://github.com/nextstrain/zika/pull/36#discussion_r1501216210 about "accession", "genbank_accession" and "url" so that we can hopefully group these changes in a PR.

**Comment by genehack** [comment]
@joverlee521 @j23414 do we still need this issue? I'm having trouble understanding the context from the linked issues — if this is still relevant, could somebody please update the description to more directly indicate what changes need to be made?

**Comment by j23414** [comment]
Can close this issue as we've dropped the "set_final_strain_name.py" script entirely during https://github.com/nextstrain/zika/pull/72

I took a quick check and both "accession" and "USVI" links work in the node call out. 

<img width="300" alt="Screenshot 2024-11-28 at 8 00 50 AM" src="https://github.com/user-attachments/assets/e468799d-c39c-493c-8678-670767808a39">

<img width="300" alt="Screenshot 2024-11-28 at 8 02 06 AM" src="https://github.com/user-attachments/assets/fc96afd1-9be0-4ea6-a276-dbb5f755ea7d">
