### ISSUE TITLE
Flatten data, results, auspice

### ISSUE THREAD

**Issue by trvrb** [nextstrain/zika#5]
I think it's unnecessary hierarchy to have:
```
build/
  - data/
  - results/
  - auspice/
```
I would flatten this to have `data/`, `results/` and `auspice/`. The intention would be that you could version `data/zika.fasta` if desired. Or drop in FASTAs. Or download via fauna.

**Comment by tsibley** [comment]
This would be fine. It would involve reverting 50bc533 and updating `.gitignore`. Would you like me to do that?

**Comment by trvrb** [comment]
I'm now waffling based on discussion in https://github.com/nextstrain/zika/issues/7. Maybe best to thread discussion of this there.
