### ISSUE TITLE
Automation cache not working as expected

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/zika#53]
I was following up on the automated workflows and noticed that [this morning's run](https://github.com/nextstrain/zika/actions/runs/8603175712) did not work as expected. The ingest job actually [uploaded new files to S3](https://github.com/nextstrain/zika/actions/runs/8603175712/job/23574461898#step:8:223). However the [cache was still the same](https://github.com/nextstrain/zika/actions/runs/8603175712/job/23574559305#step:3:11), so the phylogenetic workflow did not run.  

This made me think that the S3 hash was using the default `no_hash` instead of the actual file hashes, which I verified in my own [testing workflow](https://github.com/joverlee521/nextstrain-testing/actions/runs/8605555618/job/23582061535#step:2:22). I tried removing the default hash and saw that the [request was returning](https://github.com/joverlee521/nextstrain-testing/actions/runs/8605576058/job/23582129440#step:2:23) 
```
<botocore.awsrequest.AWSRequest object at 0x7fe3b47d2e10>
```

Based on [Stackoverflow](https://stackoverflow.com/a/74144864), this is the result of not setting a region for the request. So setting the `AWS_DEFAULT_REGION` will fix this issue in our cache.

**Comment by jameshadfield** [comment]
> this is the result of not setting a region for the request. So setting the AWS_DEFAULT_REGION will fix this issue in our cache.

Over the years I have run into a few different GitHub actions bugs because we weren't explicitly setting the region. I think it'd be good practice for us to habitually set it (just as we set the two secrets).

**Comment by joverlee521** [comment]
> Over the years I have run into a few different GitHub actions bugs because we weren't explicitly setting the region. I think it'd be good practice for us to habitually set it (just as we set the two secrets).

Yeah, I forget this all the time because the Nextstrain CLI does it automatically. I need to remember to provide it when running aws commands outside of a managed runtime...

**Comment by tsibley** [comment]
> Yeah, I forget this all the time because the Nextstrain CLI does it automatically.

It should probably stop doing that. The behaviour made some sense originally when Nextstrain CLI was only used by us and only in much more limited use cases, but it's probably time to let go of that default.
