### ISSUE TITLE
Add augur version checking

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/zika#6]
The snakemake file should store the version of augur it was tested against and compare this to the currently installed augur / containerized augur version via `augur --version` (see https://github.com/nextstrain/augur/issues/146). The code for doing this should be somewhere central (see https://github.com/nextstrain/zika/issues/2).

If the augur version is out-of-date then an error should be thrown and the snakemake file exits.

If the augur version is newer, then I think a warning is displayed but the build can proceed. If we exit on this mismatch, then all the pathogen repos have to be updated every time augur updates.

**Comment by tsibley** [comment]
https://github.com/nextstrain/zika/issues/3 exists to consider this issue more generally (not just augur).  This issue is a proposal for one approach to handling augur specifically.
