### ISSUE TITLE
What directory should auspice JSONs be saved to?

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/zika#7]
This directory, if committed to github, would be accessible from auspice (see https://github.com/nextstrain/auspice/issues/588). 
Currently this is `build/auspice`. I'd prefer a folder with a different name to just `auspice`.
Other possibilities:
* `build/auspiceJSONs`
* `build/json`
* `auspiceJSONs`

While the `nextstrain/zika` build JSONs will probably be served from S3 as opposed to github, the folder structure should be the same, just gitignored in nextstrain/* builds (except the tutorial?).

cc @trvrb @tsibley @huddlej

**Comment by tsibley** [comment]
> I'd prefer a folder with a different name to just auspice.

Can you expand upon why you'd prefer that?

I don't like those examples.  The first and last seem like just added noise without a clear reason and the second seems too generic (there are other JSON files that aren't for auspice in `build/`).

**Comment by trvrb** [comment]
I commented on this here: https://github.com/nextstrain/auspice/issues/588#issuecomment-401974513 before I realized there was an issue devoted to it. Copying text here:

> I wouldn't enforce "myLabGitHub/nextstrain-flu". I picture it being useful and (hopefully) common to have a few auspice JSONs in a repo that is largely not devoted to being a Nextstrain build. We'd do this with blab/zika-usvi for example, where we can include the tree that matches dataset used in paper, but Nextstrain is not the focus of the repo.
>
>Partly for these reasons I like using top-level "auspice/" for JSONs meant to be shared, rather than putting them in "build/auspice/" or "data/auspice/".

Folks might be using `build` or `data` for different purposes. They are very generic terms.

`build/json` seems overly generic. `auspiceJSONs` seems unnecessary. I favor something with a unique descriptive namespace. My suggestions would be:

* `auspice/`
* `nextstrain-share/`
* `nextstrain-web/`
* `nextstrain-build/`
* `nextstrain-data/`

Conceptually, this is data that's ingested by the nextstrain.org web app. Though the `nextstrain-` options don't make it obvious that these JSONs are consumed by the auspice app.

Also, I could very much see a pathogen repo like `grubaughlab/wnv` looking like:
```
wnv/
  - nextstrain-share/
  - build/
    - data/
    - results/
    - auspice/
```
Where `build/` is never versioned and added to `.gitignore` and `nextstrain-share/` is very explicitly versioned and shared with the world.

**Comment by tsibley** [comment]
Closing. With PR #8, Trevor decided on a flat layout of `data/`, `results/`, `auspice/` at the top-level for now.
