### ISSUE TITLE
Use `augur merge` to spike in USVI records

### ISSUE THREAD

**Issue by j23414** [nextstrain/zika#73]
### Description

Use the new `augur merge` feature to spike in USVI records into the phylogenetic build

### Possible solution

* [x] Add URL column to [USVI records](https://github.com/nextstrain/zika/blob/main/phylogenetic/data/metadata_usvi.tsv) and [example USVI record](https://github.com/nextstrain/zika/blob/main/phylogenetic/example_data/metadata_usvi.tsv)
* [x] Replace [csvtk merging](https://github.com/nextstrain/zika/blob/649e495a6b181c004bacae26ea4507fc6989abc5/phylogenetic/rules/merge_sequences_usvi.smk#L48-L53) with `augur merge`

**Comment by victorlin** [comment]
I'll take this as part of testing https://github.com/nextstrain/augur/pull/1601

**Comment by victorlin** [comment]
> Move [URL generation](https://github.com/nextstrain/zika/blob/649e495a6b181c004bacae26ea4507fc6989abc5/phylogenetic/rules/merge_sequences_usvi.smk#L44-L47) to ingest workflow

I ended up not doing this and [instead](https://github.com/nextstrain/zika/commit/41991ff7fa03cf92e2a6c657687f74f65a6cb425) moved both `url` and `accession` column generation to a separate rule – it seemed like the easiest thing to do for now. Maybe a separate issue can be created to move `url` and `accession` column generation to ingest?
