### ISSUE TITLE
validate produced (auspice) JSON files

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/zika#9]
see here for one way to do this https://github.com/nextstrain/augur/blob/master/tests/builds/zika/Snakefile#L196

**Comment by tsibley** [comment]
Hmm, this seems like something that `augur export` should do before it writes out the file. Why would we expect `augur export` to produce an invalid file?

**Comment by jameshadfield** [comment]
`augur export` is but one way of producing JSONs. `augur validate` is agnostic in regards to the generating function.

**Comment by tsibley** [comment]
I'm not saying we should remove `augur validate`. I'm saying that `augur export` should automatically ensure that the output it produces is valid (by calling the underlying functions in `augur.validate`).
